### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by mdntuda** [universAAL/lddi#243]
Hello everyone,

I want to integrate universAAL in a same instance with openHAB (ESH). I follow the steps given by your recommendation. At step 6 there is a typo, I think it must be: 
`feature:repo-add mvn:org.universAAL.lddi/lddi.karaf.feature/3.4.2-SNAPSHOT/xml/features`

After adding this feature, without any problem, I continue with step 7, but there is no feature called: `uAAL-LDDI.Smarthome` there is only `uAAL-LDDI` and some others:
 `openhab> feature:install uAAL-LDDI
uAAL-LDDI                                                                                     (The LDDI framework for KNX based on the uAAL-MW)
uAAL-LDDI-ZWAVE                                                                             (The LDDI framework for ZWave based on the uAAL-MW)
uAAL-LDDI-ZigBee                                                                           (The LDDI framework for ZigBee based on the uAAL-MW)
uAAL-LDDI-Abstraction      (Defines the interfaces to be used in addition to ontologies for linking the access and integration layers of LDDI.)
uAAL-LDDI-BluetoothContinua (The Continua Bluetooth Heath Personal Device Manager. Remember to install the apropriate drivers for your system.)
`. 

Even for installing `uAAL-LDDI` I get some error for dependencies, which I don't really understand because of the package structure. It would be nice if someone can tell me how to deal with these kind of problems. The error look like this: 
`openhab> feature:install uAAL-LDDI
Error executing command: Error:
        Error downloading mvn:org.apache.felix/org.apache.felix.devicemanager/0.9.0-SNAPS
        Error downloading mvn:jaxen/jaxen/1.1.3
        Error downloading mvn:jaxen/jaxen/1.1.3
        Error downloading mvn:org.jdom/jdom/1.1.3
        Error downloading mvn:org.jdom/jdom/1.1.3
        Error downloading mvn:org.apache.felix/org.apache.felix.dependencymanager/3.1.0`

Thank you for your time.

Best regards,
mdntuda

PS: I am using openHAB 2.3 to try, I know I shouldn't (recommended only for 2.2.0 and before) but just out of curiosity.

**Comment by Alfiva** [comment]
Hello, thanks for trying this out. Actually there is no typo, the right feature collection is the one in the wiki: mvn:org.universAAL.lddi/lddi.smarthome.karaf.feature/3.4.2-SNAPSHOT/xml/features
The problem is that we hadn't deployed the 3.4.2-S version to the Maven repository yet, so it was not available, sorry. Without this collection, you couldn't find the LDDI.Smarthome feature, which is the one you need. If you uyse only uAAL-LDDI it will not work, it is just an "importable" feature, it does nothing on its own and may lead to those problems you report.
I have just deployed the 3.4.2-S version of the feature collection to our repo, so please give it another try (with the original instructions) and let us know if you find any problem.

**Comment by mdntuda** [comment]
Thank Alfiva for your quick respond,

I go through the steps again, in the 7th step, I get this error: 
`openhab> feature:install uAAL-LDDI.Smarthome
Error executing command: Error:
        Error downloading mvn:org.jgroups/jgroups/3.4.1.Final `

Maybe there is some package missing.

Best regards,
mdntuda

**Comment by Alfiva** [comment]
Do you have more info on the error? That jar is available in the Maven central repository so there shouldn't be any problem downloading it... Is it that it cannot download or that it cannot install properly? It shouldn't have any particular dependency that I remember...
Try installing it alone in openhab, before doing anything with universAAL (try either with install command or putting it on deploy folder) to figure out what the problem is.

**Comment by mdntuda** [comment]
Hi Alfiva,

I don't know how I can get more information about the error (log:display is showing nothing). According to the failure showed, it is some kind of downloading error, since you are absolutly right, that jgroups is a public package available from maven repository.

Anyhow, with help of my collegue, we manage to make it run. These are the steps we did:
i) edit the file `org.ops4j.pax.url.mvn.cfg` uncomment the line `org.ops4j.pax.url.mvn.localRepository=C:/Users/Alfiva/.m2/repository` and choose the right username for .m2 folder.

ii) I download the bundle `jgroups-3.4.1.Final` from Maven repository, copy it inside the folder: `C:\Users\USERNAME-TO-SET\.m2\repository\org\jgroups\jgroups\3.4.1.Final` 

iii) Start ESH and execute the command: `feature:install uAAL-LDDI.Smarthome` and it works for both ESH  2.2.0 and 2.3.0. 

Thank you for your help!

Best regards,
mdntuda

**Comment by Alfiva** [comment]
Adding the Maven central repo to the list of repositories in that config file should also work, I guess, but I don't know why it's not contacted by default in your case... Anyway, good to know it finally worked
